project_name: blogit

release:
  github:
    owner: caixw
    name: blogit
  name_template: '{{.Tag}}'

builds:
- id: blogit

  goos:
  - darwin
  - linux
  - windows

  goarch:
  - amd64
  - arm64

  ignore:
  - goos: windows
    goarch: arm64

  main: ./cmd/blogit

  binary: blogit

  flags:
  - -trimpath

  ldflags:
  - -s -w -X github.com/caixw/blogit/internal/vars.metadata=.metadata={{time "20060102"}}.{{.Commit}}

  env:
  - CGO_ENABLED=0

brews:
- tap:
    owner: caixw
    name: homebrew-brew
  url_template: "https://github.com/caixw/blogit/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  folder: Formula
  homepage: "https://github.com/caixw/blogit"
  description: 静态博客生成工具
  license: MIT


dockers:
  -
    ids: ['blogit']
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile

    image_templates:
    - "docker.io/caixw/blogit:{{ .Tag }}"
    - "docker.io/caixw/blogit:v{{ .Major }}"
    - "docker.io/caixw/blogit:v{{ .Major }}.{{ .Minor }}"
    - "docker.io/caixw/blogit:latest"

    - "ghcr.io/caixw/blogit:{{ .Tag }}"
    - "ghcr.io/caixw/blogit:v{{ .Major }}"
    - "ghcr.io/caixw/blogit:v{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/caixw/blogit:latest"

archives:
- builds:
  - blogit
  replacements:
    darwin: macOS
  format_overrides:
  - goos: windows
    format: zip
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  skip: true
