name: blogit-build
description: 生成静态博客
author: caixw <https://caixw.io>

branding:
  icon: book
  color: green

inputs:
  version:
    required: true
    description: blogit 的版本号，可以使用 latest 指定最新版本
    default: latest

  dest:
    required: true
    description: 编译后的输出目录

  src:
    required: true
    description: 源码目录

runs:
  using: docker
  image: docker://caixw/blogit:${{ input.version }}
  args:
  - build
  - -src=${{ input.src }}
  - -dest=${{ input.dest }}
