name: blogit-build
description: 生成静态博客
author: caixw <https://caixw.io>

branding:
  icon: book
  color: green

inputs:
  dest:
    required: true
    description: 编译后的输出目录

  src:
    required: true
    description: 源码目录

runs:
  using: docker
  image: docker://caixw/blogit:latest
  args: ['build', '-src=${{ inputs.src }}', '-dest=${{ inputs.dest }}']
